modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="nuclearcoremod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="NuclearCore" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java and Cats" #optional
authors="CatDev, 1mag1n33Dev" #optional
description='''
meow. Nuclear plant goes boom.
'''
[[dependencies.nuclearcoremod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nuclearcoremod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nuclearcoremod]]
    modId="geckolib3"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
